### ISSUE TITLE
The future of this repo.

### ISSUE THREAD

**Issue by RobertJGabriel** [OpenDyslexic/extension#47]
Just giving a small update.

Over the next few weeks, I will me merging Firefox repo into this, plus renaming it.

Along with that.

- Will be launching it on Edge and iOs and Safrai.

If anyone has any suggestions or improvements just let me know.

Thank you
Robert James Gabriel

**Comment by brunodOut** [comment]
@RobertJGabriel may I use this post to ask an offtopic question regarding the font (not the extension)? I hope you don't mind. What is 1) the proper place to obtain instructions on how to build OpenDyslexic fonts, and 2) the right repository for obtaining current sources and builds?

I am very confused by this and cannot understand the way the project is structured or where should I get all the font files, including OpenDyslexic Mono (maybe because I'm autistic, or maybe it's hard for everyone else, not sure). It seems like linux distributions' packagers might be confused too. For instance, as you can see here, Fedora packagers are having a hard time to figure out the repository structure: https://bugzilla.redhat.com/show_bug.cgi?id=1999240 and a user mentioned this repo as a place to obtain the package.

It looks like you work closely with OpenDyslexic, so I  was hoping you could offer some guidance for me (and maybe for the packagers at the Fedora bug report in the link).

**Comment by RobertJGabriel** [comment]
Hello everyone,

Just an update, I have this rebuilt for manifest V3. So see the changes in the next few hours.
